# Generated by Django 4.2.7 on 2025-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_materialcompletion_coursecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Teacher blocked this student from the course'),
        ),
    ]
